---
- name: CONFIGURE VTY
  hosts: R1
  gather_facts: false
  connection: local

  tasks:
   - name: Create ACL
     ios_config:
       parents: ip access-list standard VTY
       lines:
        - permit 192.168.10.10
        - permit 192.168.20.20
        
   - name: Apply ACL
     ios_config:
       parents: line vty 0 4
       lines:
        - access-class VTY in
        
   - name: SHOW ACL 
     ios_command:
       commands:
         - show access-lists
     register: output
